### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by jimmyrekso** [jimmyrekso/SEBC#2]

**Comment by jimmyrekso** [comment]
Finish install & config mariadb
![image](https://cloud.githubusercontent.com/assets/25733319/22930757/d8249be4-f2fc-11e6-998d-339f0b110ac5.png)

**Comment by jimmyrekso** [comment]
Finish install cloudera Server
![image](https://cloud.githubusercontent.com/assets/25733319/22930790/02e25a60-f2fd-11e6-9116-6ab246d77d34.png)

**Comment by jimmyrekso** [comment]
Got problem when add cluster
![image](https://cloud.githubusercontent.com/assets/25733319/22931224/d1dddf00-f2fe-11e6-8bee-b48c88ac1850.png)

![image](https://cloud.githubusercontent.com/assets/25733319/22931240/e17ca31a-f2fe-11e6-9a61-cfc603ddab27.png)

**Comment by mfernest** [comment]
Since your error indicates certain network ports aren't responding, check to see if any firewall rukes are running on the node.

**Comment by jimmyrekso** [comment]
Firewall disabled already

**Comment by jimmyrekso** [comment]
Last issue already solved by change the pattern of FQDN.
Another issue when to connect database for HUE
 
![image](https://cloud.githubusercontent.com/assets/25733319/22961364/5b8dd31e-f380-11e6-8ea0-ddd173044ec2.png)

**Comment by jimmyrekso** [comment]
It seems, Cloudera Manager read my wrong python
![image](https://cloud.githubusercontent.com/assets/25733319/22962608/d5f32804-f388-11e6-9a0b-16c56f6863bc.png)


My node already python 2.7 installed
![image](https://cloud.githubusercontent.com/assets/25733319/22962626/035491ca-f389-11e6-8593-6dea6921cb97.png)

**Comment by jimmyrekso** [comment]
I tried to reinstall everything, then quite good until process to first running HDFS

![image](https://cloud.githubusercontent.com/assets/25733319/22990691/fb41f330-f3f4-11e6-8b30-8625ff277d78.png)

**Comment by jimmyrekso** [comment]
Finally i have finished installation
![image](https://cloud.githubusercontent.com/assets/25733319/23004230/7169776e-f430-11e6-8b06-434d9b59538d.png)
