### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by jimmyrekso** [jimmyrekso/SEBC#3]
https://github.com/jimmyrekso/SEBC/blob/master/challenges/labs/2_cmd.md
https://github.com/jimmyrekso/SEBC/blob/master/challenges/labs/1_my-database-server.repo.md
https://github.com/jimmyrekso/SEBC/blob/master/challenges/labs/0_setup.md

**Comment by mfernest** [comment]
`2_cloudera-manager.repo.md` - not submitted
`2_db.properties.md` - not submitted
