### ISSUE TITLE
Kerberize the cluster

### ISSUE THREAD

**Issue by jimmyrekso** [jimmyrekso/SEBC#6]
Still working with kerberos :(
https://github.com/jimmyrekso/SEBC/blob/master/challenges/labs/images/kerberos.png

**Comment by jimmyrekso** [comment]
[https://github.com/jimmyrekso/SEBC/blob/master/challenges/labs/images/kerberos.png](url)

**Comment by jimmyrekso** [comment]
Not finish yet

**Comment by mfernest** [comment]
Not submitted.
